'use strict';
(async()=>{
  try{
    const OFFLINE_USER='kt_offline_user_v1';let j=null,offlineSession=false;
    try{const r=await fetch('/api/auth?action=me',{cache:'no-store'});if(!r.ok){if(r.status===401||r.status===403){localStorage.removeItem(OFFLINE_USER);location.replace('/login.html');return;}throw new Error('Auth unavailable')}j=await r.json();if(j?.user)localStorage.setItem(OFFLINE_USER,JSON.stringify({user:j.user,saved_at:new Date().toISOString()}));}
    catch(e){if(navigator.onLine)throw e;try{const saved=JSON.parse(localStorage.getItem(OFFLINE_USER)||'null');if(!saved?.user)throw e;j={user:saved.user};offlineSession=true}catch{location.replace('/login.html');return}}
    window.KT_USER=j.user;window.KT_OFFLINE_SESSION=offlineSession;const access=new Set(j.user.access||[]),isAdmin=j.user.designation==='admin';
    document.querySelectorAll('#nav [data-view]').forEach(b=>{if(!access.has(b.dataset.view)&&!(b.dataset.view==='dashboard'&&!isAdmin))b.style.display='none';});
    document.querySelectorAll('#nav .section').forEach(s=>{let n=s.nextElementSibling,visible=false;while(n&&!n.classList.contains('section')&&!n.classList.contains('navfoot')){if(n.matches?.('[data-view]')&&n.style.display!=='none')visible=true;n=n.nextElementSibling;}if(!visible)s.style.display='none';});
    const hero=document.querySelector('.hero');if(hero){const names={admin:'Admin Dashboard',manager:'Manager Dashboard',accountant:'Accountant Dashboard',salesman:'Sales Dashboard'};hero.querySelector('h1').textContent=names[j.user.designation]||'Kashif Traders';hero.querySelector('p').textContent=offlineSession?'Offline Mode • cached records aur Pending Sync available hain.':'Your dashboard reflects the access assigned by Admin.';}
    const status=document.getElementById('status');if(status)status.textContent=offlineSession?'OFFLINE • '+(j.user.full_name||j.user.employee_code):(j.user.full_name||j.user.employee_code)+' • '+String(j.user.designation||'').toUpperCase();
    const dashboard=document.getElementById('dashboard'),module=document.getElementById('module');dashboard?.classList.add('hidden');module?.classList.add('hidden');
    const load=src=>new Promise((ok,bad)=>{const s=document.createElement('script');s.src=src;s.async=true;s.onload=ok;s.onerror=bad;document.body.appendChild(s);});
    const offline=()=>load('/offline-sync.js?v=20260913-offline4').catch(e=>console.error('Offline feature unavailable',e));
    const extras=()=>Promise.all([load('/document-scan.js?v=20260913-clientbill1'),load('/supplier-bill-pdf-ui.js?v=20260913-supplierpdf1'),load('/supplier-payment-pdf-ui.js?v=20260913-supplierpaymentpdf1')]).catch(e=>console.error('Document/PDF feature unavailable',e));
    const salaryExtras=()=>load('/salary-statement-enhance.js?v=20260912-pdf1').catch(e=>console.error('Salary statement enhancement unavailable',e));
    const installExcelExports=()=>{if(!isAdmin)return;const map={suppliers:'suppliers','supplier-payments':'supplier_payments',clients:'clients','client-sales':'client_invoices','client-receipts':'client_receipts',products:'products','goods-receiving':'goods_receiving','inventory-ledger':'inventory_ledger',warehouses:'warehouses','warehouse-stock':'warehouse_stock','stock-transfer':'stock_transfers','stock-adjustment':'stock_adjustments',documents:'documents',employees:'employees','salary-advances':'salary_requests'};const download=async(type,button)=>{if(!navigator.onLine){if(typeof toast==='function')toast('Excel export ke liye internet required hai.',true);return}const old=button.textContent;button.disabled=true;button.textContent=type==='complete_backup'?'Preparing Backup…':'Exporting…';try{const x=await fetch('/api/payment-whatsapp?type=excel_export&export_type='+encodeURIComponent(type),{cache:'no-store'});if(!x.ok){const e=await x.json().catch(()=>({}));throw new Error(e.error||'Excel export failed')}const raw=await x.blob(),isBackup=type==='complete_backup',blob=isBackup?new Blob([raw],{type:'application/zip'}):raw,dis=x.headers.get('content-disposition')||'',m=dis.match(/filename="?([^";]+)"?/i),name=isBackup?('Kashif-Traders-Excel-Backup-'+new Date().toISOString().slice(0,10)+'.zip'):(m?.[1]||('Kashif-Traders-'+type+'-'+new Date().toISOString().slice(0,10)+'.xlsx')),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);if(typeof toast==='function')toast(isBackup?'Complete Excel backup downloaded':'Excel exported')}catch(e){if(typeof toast==='function')toast(e.message||'Excel export failed',true);else console.error(e)}finally{button.disabled=false;button.textContent=old}};const addButton=(host,type,label,key,primary=false)=>{if(!host||document.querySelector('#module [data-common-excel="'+key+'"]'))return;const b=document.createElement('button');b.className=primary?'btn':'btn light';b.dataset.commonExcel=key;b.textContent=label;b.addEventListener('click',()=>download(type,b));host.appendChild(b)};const enhance=()=>{const active=document.querySelector('#nav [data-view].active'),view=active?.dataset.view||'';if(!view||view==='dashboard')return;const host=document.querySelector('#module .toolbar')||document.querySelector('#module .modulehead')||document.querySelector('#module .actions');const type=map[view];if(type)addButton(host,type,'Export Excel',type);if(view==='supplier-bills')addButton(host,'supplier_bill_items','Export Bill Items','supplier_bill_items');if(view==='settings')addButton(host,'complete_backup','Export Complete Excel Backup','complete_backup',true)};const ob=new MutationObserver(()=>enhance());if(module)ob.observe(module,{childList:true,subtree:true});document.getElementById('nav')?.addEventListener('click',()=>setTimeout(enhance,0));setTimeout(enhance,0)};
    if(isAdmin&&access.has('dashboard')){await load('/admin-dashboard-fix.js?v=20260913-admin9');if(typeof window.KT_OPEN_ADMIN_DASHBOARD==='function')window.KT_OPEN_ADMIN_DASHBOARD();document.body.classList.add('auth-ready');offline();Promise.all(['/app.js?v=20260914-menuscroll1','/inventory-ui.js?v=20260911-rbac3','/product-status-fix.js?v=20260910-status1','/products-scalable.js?v=20260911-barcode1','/employees-ui.js?v=20260911-rbac3','/salary-ui.js?v=20260912-polish2','/role-dashboard.js?v=20260911-rbac6'].map(load)).then(()=>{salaryExtras();extras();installExcelExports()}).catch(console.error);return;}
    await offline();const core=['/app.js?v=20260914-menuscroll1','/inventory-ui.js?v=20260911-rbac3','/product-status-fix.js?v=20260910-status1','/products-scalable.js?v=20260911-barcode1','/employees-ui.js?v=20260911-rbac3','/salary-ui.js?v=20260912-polish2','/role-dashboard.js?v=20260911-rbac6'];await Promise.all(core.map(load));salaryExtras();extras();installExcelExports();const dash=document.querySelector('#nav [data-view="dashboard"]');if(!isAdmin&&dash){dashboard?.classList.add('hidden');module?.classList.add('hidden');dash.style.display='';dash.classList.add('active');document.body.classList.add('auth-ready');dash.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true}));return;}const first=[...document.querySelectorAll('#nav [data-view]')].find(b=>b.style.display!=='none');if(first)first.click();document.body.classList.add('auth-ready');
  }catch(e){console.error(e);if(!navigator.onLine&&localStorage.getItem('kt_offline_user_v1'))document.body.classList.add('auth-ready');else location.replace('/login.html');}
})();
