'use strict';
(()=>{
 const cameraViews=new Set(['supplier-payments','client-sales','client-receipts']);
 const fieldFor=()=> 'attachment_url';
 const $=(root,sel)=>root.querySelector(sel);
 function note(msg,bad=false){if(typeof toast==='function')toast(msg,bad);}
 async function compressImage(file){if(!file.type.startsWith('image/'))return file;if(file.size<1800000)return file;const bmp=await createImageBitmap(file),max=1800,scale=Math.min(1,max/Math.max(bmp.width,bmp.height));const c=document.createElement('canvas');c.width=Math.round(bmp.width*scale);c.height=Math.round(bmp.height*scale);c.getContext('2d').drawImage(bmp,0,0,c.width,c.height);bmp.close?.();const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.82));return new File([blob],file.name.replace(/\.[^.]+$/,'.jpg'),{type:'image/jpeg'});}
 function setValue(form,name,value){if(value===undefined||value===null||value==='')return;const el=form.elements[name];if(el&&!el.value)el.value=value;}
 async function scan(file,form,box){if(!file?.type.startsWith('image/')){note('OCR ke liye image/photo select karein.',true);return false;}box.textContent='Reading document…';try{const f=await compressImage(file),data=await new Promise((ok,bad)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=bad;r.readAsDataURL(f)}),res=await fetch('/api/ocr',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dataUrl:data,view:currentView})}),j=await res.json().catch(()=>({}));if(!res.ok)throw Error(j.error||'OCR failed');const x=j.fields||{};setValue(form,'invoice_number',x.invoice_number);setValue(form,'invoice_date',x.date);setValue(form,'due_date',x.due_date);setValue(form,'payment_date',x.date);setValue(form,'receipt_date',x.date);setValue(form,'amount',x.amount);setValue(form,'reference_number',x.reference_number);setValue(form,'bank',x.bank);if(currentView==='supplier-payments'||currentView==='client-receipts'){const method=form.elements.payment_method;if(method)method.value='BANK';}box.textContent='AI read complete — details verify karke Save karein.';return true}catch(e){box.textContent='AI read nahi hua — manually verify/fill karein.';note(e.message,true);return false}}
 async function upload(file,form,box,quiet=false){if(!file)return false;try{const f=await compressImage(file),res=await fetch('/api/upload-document?name='+encodeURIComponent(f.name),{method:'POST',headers:{'Content-Type':f.type||'application/octet-stream'},body:f}),j=await res.json().catch(()=>({}));if(!res.ok)throw Error(j.error||'Upload failed');const el=form.elements[fieldFor()];if(el)el.value=j.url;if(!quiet)box.textContent='Document attached.';return true}catch(e){if(!quiet)note(e.message,true);return false}}
 async function process(file,form,status,buttons){buttons.forEach(b=>b.disabled=true);try{const ok=await scan(file,form,status);const attached=await upload(file,form,status,true);status.textContent=ok?(attached?'AI read + image attached. Verify and Save.':'AI read complete. Verify and Save.'):(attached?'Image attached; details manually verify karein.':'Image read/upload failed.');}finally{buttons.forEach(b=>b.disabled=false)}}
 function enhance(){if(!cameraViews.has(currentView))return;const modal=document.getElementById('modal'),form=document.getElementById('recordForm');if(!modal||!form||form.dataset.scanReady)return;form.dataset.scanReady='1';const url=form.elements[fieldFor()];if(!url)return;url.closest('.field')?.style.setProperty('display','none');const payment=currentView==='supplier-payments'||currentView==='client-receipts';const panel=document.createElement('div');panel.className='field full';panel.innerHTML='<label>'+(payment?'Bank Transfer Slip':'Client Bill Image')+'</label><input id="ktCameraFile" type="file" accept="image/*" capture="environment" style="display:none"><input id="ktGalleryOcr" type="file" accept="image/*" style="display:none"><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:4px"><button type="button" class="btn light" id="ktScanBtn">📷 Camera</button><button type="button" class="btn light" id="ktGalleryBtn">🖼 Gallery</button></div><small id="ktScanStatus" style="display:block;margin-top:7px">'+(payment?'Bank slip ki photo se payment details read hongi. Cash payment manual entry rahegi.':'Client bill ki photo se invoice details read hongi.')+'</small>';$(form,'.grid')?.appendChild(panel);const camera=$(panel,'#ktCameraFile'),gallery=$(panel,'#ktGalleryOcr'),status=$(panel,'#ktScanStatus'),scanBtn=$(panel,'#ktScanBtn'),galleryBtn=$(panel,'#ktGalleryBtn'),buttons=[scanBtn,galleryBtn];scanBtn.onclick=()=>camera.click();galleryBtn.onclick=()=>gallery.click();camera.onchange=async()=>{if(camera.files?.[0])await process(camera.files[0],form,status,buttons);camera.value=''};gallery.onchange=async()=>{if(gallery.files?.[0])await process(gallery.files[0],form,status,buttons);gallery.value=''};}
 new MutationObserver(()=>{try{enhance()}catch(e){console.error('Document scan UI',e)}}).observe(document.body,{childList:true,subtree:true});
})();
