(()=>{
 const $=id=>document.getElementById(id),money=v=>'PKR '+Number(v||0).toLocaleString('en-PK'),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])),stamp=v=>new Date(v).toLocaleString('en-PK');let status='all',rows=[];
 $('back').onclick=()=>location.href='/cashier-sales.html';
 async function request(url,opt){const r=await fetch(url,opt),j=await r.json().catch(()=>({}));if(r.status===401){location.replace('/login.html');throw Error('Login required')}if(!r.ok)throw Error(j.error||'Request failed');return j}
 const items=x=>Array.isArray(x.items)?x.items:JSON.parse(x.items||'[]');
 function render(){$('summary').textContent=rows.length+' online orders';$('orders').innerHTML=rows.length?rows.map(x=>'<article class="order"><div class="order-head"><div><h2>'+esc(x.invoice_number)+'</h2><div class="meta">Order: '+esc(x.order_number)+'<br><b>'+esc(x.customer_name)+'</b> · '+esc(x.phone)+'<br>'+stamp(x.created_at)+' · '+esc(x.fulfilment_type==='pickup'?'Shop Pickup':'Delivery')+(x.delivery_address?'<br>'+esc(x.delivery_address):'')+'<br>Payment: '+esc(x.payment_method)+' · '+esc(x.payment_status)+(x.payment_reference?' · Ref: '+esc(x.payment_reference):'')+'</div></div><span class="badge">'+esc(String(x.status).replaceAll('_',' ').toUpperCase())+'</span></div><div class="items">'+items(x).map(i=>'<div class="item"><span>'+esc(i.name)+' × '+esc(i.qty)+' '+esc(i.unit)+'</span><b>'+money(i.total)+'</b></div>').join('')+'</div><div class="totals"><span>Total</span><b>'+money(x.total)+'</b></div><div class="action"><select data-status-select="'+x.id+'"><option value="new">New</option><option value="confirmed">Confirmed</option><option value="ready">Ready</option><option value="out_for_delivery">Out for Delivery</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><button data-update="'+x.id+'">Update Status</button><button data-paid="'+x.id+'" '+(x.payment_status==='paid'?'disabled':'')+'>'+(x.payment_status==='paid'?'Payment Paid':'Mark Payment Paid')+'</button><button class="primary" data-print="'+x.id+'">Print Invoice</button><button class="primary" data-share="'+x.id+'">PDF Share</button></div></article>').join(''):'<div class="empty">Is status mein koi online order nahi.</div>';
  rows.forEach(x=>{const s=document.querySelector('[data-status-select="'+x.id+'"]');if(s)s.value=x.status});document.querySelectorAll('[data-update]').forEach(b=>b.onclick=()=>patch(b.dataset.update,{status:document.querySelector('[data-status-select="'+b.dataset.update+'"]').value}));document.querySelectorAll('[data-paid]').forEach(b=>b.onclick=()=>patch(b.dataset.paid,{payment_status:'paid'}));document.querySelectorAll('[data-print]').forEach(b=>b.onclick=()=>printInvoice(find(b.dataset.print)));document.querySelectorAll('[data-share]').forEach(b=>b.onclick=()=>shareInvoice(find(b.dataset.share)))}
 const find=id=>rows.find(x=>String(x.id)===String(id));
 function invoiceLines(x){const lines=['KASHIF TRADERS','E-Commerce Invoice',x.invoice_number,'Order: '+x.order_number,'Date: '+stamp(x.created_at),'Customer: '+x.customer_name,'Phone: '+x.phone,'Order Type: '+x.fulfilment_type,'Payment: '+x.payment_method+' / '+x.payment_status,''];items(x).forEach(i=>lines.push(i.name+' | '+i.qty+' '+i.unit+' x '+i.rate+' = '+i.total));lines.push('','Subtotal: '+money(x.subtotal),'Delivery: '+money(x.delivery_fee),'Grand Total: '+money(x.total));return lines}
 function printInvoice(x){if(!x)return;const w=window.open('','_blank','width=560,height=760');if(!w)return alert('Pop-ups allow karein');w.document.write('<!doctype html><title>'+esc(x.invoice_number)+'</title><style>body{font:14px Arial;max-width:430px;margin:25px auto}.line{padding:6px;border-bottom:1px dashed #ccc}.line:first-child{font:bold 24px Georgia;text-align:center;border:0}</style>'+invoiceLines(x).map(v=>'<div class="line">'+esc(v||' ')+'</div>').join('')+'<script>onload=()=>print()<\/script>');w.document.close()}
 function pdfBlob(lines){const safe=s=>String(s).replace(/([\\()])/g,'\\$1').replace(/[^\x20-\x7E]/g,'?'),stream='BT /F1 11 Tf 45 800 Td '+lines.slice(0,42).map((l,i)=>(i?'0 -17 Td ':'')+'('+safe(l)+') Tj').join(' ')+' ET',objs=['1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj','2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj','3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj','4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj','5 0 obj << /Length '+stream.length+' >> stream\n'+stream+'\nendstream endobj'];let pdf='%PDF-1.4\n',off=[0];objs.forEach(o=>{off.push(pdf.length);pdf+=o+'\n'});const pos=pdf.length;pdf+='xref\n0 6\n0000000000 65535 f \n'+off.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer << /Size 6 /Root 1 0 R >>\nstartxref\n'+pos+'\n%%EOF';return new Blob([pdf],{type:'application/pdf'})}
 async function shareInvoice(x){if(!x)return;const blob=pdfBlob(invoiceLines(x)),file=new File([blob],x.invoice_number+'.pdf',{type:'application/pdf'});try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]})))await navigator.share({files:[file],title:'Kashif Traders E-Commerce Invoice'});else{const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)}}catch(e){if(e.name!=='AbortError')alert(e.message)}}
 async function patch(id,data){try{await request('/api/ecommerce?action=manage&id='+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});await load()}catch(e){alert(e.message)}}
 async function load(){try{const j=await request('/api/ecommerce?action=manage&status='+status,{cache:'no-store'});rows=j.records||[];render()}catch(e){$('orders').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}
 $('refresh').onclick=load;document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>{status=b.dataset.status;document.querySelectorAll('[data-status]').forEach(x=>x.classList.toggle('active',x===b));load()});load();setInterval(load,15000)
})();
