import {neon} from '@neondatabase/serverless';
import {getSessionUser} from './api/_auth.js';

const db=()=>{const u=process.env.DATABASE_URL;if(!u)throw Error('DATABASE_URL_NOT_CONFIGURED');return neon(u)};
const clean=v=>v===undefined||v===null?null:String(v).trim()||null;
const asId=v=>{const n=Number(v);return Number.isInteger(n)&&n>0?n:null};
const body=req=>typeof req.body==='string'?JSON.parse(req.body||'{}'):(req.body||{});
const imageList=value=>{let list=value;if(typeof list==='string'){try{list=JSON.parse(list)}catch{list=[]}}return(Array.isArray(list)?list:[]).map(clean).filter(Boolean).slice(0,3)};
const isKgUnit=unit=>['kg','kgs','kilogram','kilograms'].includes(String(unit||'').trim().toLowerCase());
let schemaReady=false;
async function schema(sql){if(schemaReady)return;await sql`CREATE TABLE IF NOT EXISTS ecommerce_settings(id SMALLINT PRIMARY KEY DEFAULT 1 CHECK(id=1),store_name TEXT NOT NULL DEFAULT 'Kashif Traders',contact_phone TEXT,shop_address TEXT,bank_details TEXT,easypaisa_number TEXT,jazzcash_number TEXT,delivery_fee NUMERIC(14,2) NOT NULL DEFAULT 0,updated_at TIMESTAMPTZ NOT NULL DEFAULT now())`;await sql`INSERT INTO ecommerce_settings(id) VALUES(1) ON CONFLICT(id) DO NOTHING`;await sql`CREATE TABLE IF NOT EXISTS ecommerce_products(id BIGSERIAL PRIMARY KEY,sku TEXT UNIQUE NOT NULL,name TEXT NOT NULL,category TEXT,description TEXT,unit TEXT NOT NULL DEFAULT 'pcs',sale_price NUMERIC(14,2) NOT NULL DEFAULT 0,stock_quantity NUMERIC(14,3) NOT NULL DEFAULT 0,product_image_url TEXT,status TEXT NOT NULL DEFAULT 'active',created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now())`;await sql`ALTER TABLE ecommerce_products ADD COLUMN IF NOT EXISTS product_image_urls JSONB NOT NULL DEFAULT '[]'::jsonb`;await sql`UPDATE ecommerce_products SET product_image_urls=jsonb_build_array(product_image_url) WHERE product_image_url IS NOT NULL AND trim(product_image_url)<>'' AND jsonb_array_length(product_image_urls)=0`;await sql`CREATE INDEX IF NOT EXISTS ecommerce_products_catalog_idx ON ecommerce_products(status,category,name)`;await sql`CREATE TABLE IF NOT EXISTS ecommerce_categories(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'active',created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now())`;await sql`CREATE UNIQUE INDEX IF NOT EXISTS ecommerce_categories_name_uidx ON ecommerce_categories(lower(name))`;await sql`INSERT INTO ecommerce_categories(name) SELECT MIN(trim(category)) FROM ecommerce_products WHERE category IS NOT NULL AND trim(category)<>'' GROUP BY lower(trim(category)) ON CONFLICT DO NOTHING`;await sql`CREATE TABLE IF NOT EXISTS ecommerce_promotions(id BIGSERIAL PRIMARY KEY,title TEXT,subtitle TEXT,media_type TEXT NOT NULL,media_url TEXT NOT NULL,link_url TEXT,status TEXT NOT NULL DEFAULT 'active',sort_order INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS ecommerce_orders(
  id BIGSERIAL PRIMARY KEY,order_number TEXT UNIQUE NOT NULL,invoice_number TEXT UNIQUE NOT NULL,customer_name TEXT NOT NULL,phone TEXT NOT NULL,email TEXT,
  fulfilment_type TEXT NOT NULL,delivery_address TEXT,payment_method TEXT NOT NULL,payment_reference TEXT,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,subtotal NUMERIC(14,2) NOT NULL DEFAULT 0,delivery_fee NUMERIC(14,2) NOT NULL DEFAULT 0,
  total NUMERIC(14,2) NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'new',payment_status TEXT NOT NULL DEFAULT 'unpaid',
  notes TEXT,amount_received NUMERIC(14,2),paid_by_name TEXT,paid_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
)`;await sql`CREATE INDEX IF NOT EXISTS ecommerce_orders_status_idx ON ecommerce_orders(status,created_at DESC)`;schemaReady=true}
async function catalog(sql,req){const search=clean(req.query?.search)||'',like=`%${search}%`,category=clean(req.query?.category)||'';return sql`SELECT p.id,p.sku,p.name,p.category,p.description,p.unit,p.sale_price,p.product_image_url,p.product_image_urls,p.stock_quantity::numeric stock
 FROM ecommerce_products p WHERE p.status='active' AND p.sale_price>0 AND p.stock_quantity>0
 AND (${search}='' OR p.name ILIKE ${like} OR COALESCE(p.sku,'') ILIKE ${like} OR COALESCE(p.category,'') ILIKE ${like})
 AND (${category}='' OR lower(COALESCE(p.category,''))=lower(${category})) ORDER BY p.category,p.name LIMIT 300`}
async function createOrder(sql,req){const b=body(req),name=clean(b.customer_name),phone=clean(b.phone),fulfilment=clean(b.fulfilment_type),method=clean(b.payment_method),requested=Array.isArray(b.items)?b.items:[];
 if(!name||!phone)return{status:400,data:{error:'Customer name aur phone required hain'}};
 if(!['delivery','pickup'].includes(fulfilment))return{status:400,data:{error:'Delivery ya pickup select karein'}};
 if(fulfilment==='delivery'&&!clean(b.delivery_address))return{status:400,data:{error:'Delivery address required hai'}};
 if(!['Cash on Delivery','Bank Transfer','EasyPaisa','JazzCash'].includes(method))return{status:400,data:{error:'Valid payment method select karein'}};
 const qtyMap=new Map();for(const x of requested){const pid=asId(x.product_id),q=Number(x.qty);if(pid&&Number.isFinite(q)&&q>0)qtyMap.set(pid,Math.min(999,Number(((qtyMap.get(pid)||0)+q).toFixed(3))))}const ids=[...qtyMap.keys()];if(!ids.length)return{status:400,data:{error:'Cart mein product add karein'}};
 const rows=await sql`SELECT p.id,p.name,p.unit,p.sale_price,p.stock_quantity::numeric stock FROM ecommerce_products p WHERE p.id=ANY(${ids}::bigint[]) AND p.status='active'`;
 if(rows.length!==ids.length)return{status:409,data:{error:'Cart ka koi product ab available nahi'}};
 const items=[];for(const p of rows){const qty=qtyMap.get(Number(p.id)),stock=Number(p.stock||0),kg=isKgUnit(p.unit);if(kg){if(qty<0.25||Math.abs(qty*4-Math.round(qty*4))>0.000001)return{status:400,data:{error:`${p.name}: minimum 250 gram aur 250 gram steps allowed hain`}}}else if(qty<1||!Number.isInteger(qty))return{status:400,data:{error:`${p.name}: quantity whole number honi chahiye`}};if(qty>stock)return{status:409,data:{error:`${p.name}: required quantity available nahi hai`}};items.push({product_id:Number(p.id),name:p.name,unit:p.unit,qty,rate:Number(p.sale_price),total:qty*Number(p.sale_price)})}
 if(method!=='Cash on Delivery'&&!clean(b.payment_reference))return{status:400,data:{error:'Transaction reference required hai'}};
 const settings=(await sql`SELECT delivery_fee FROM ecommerce_settings WHERE id=1`)[0],subtotal=items.reduce((n,x)=>n+x.total,0),deliveryFee=fulfilment==='delivery'?Math.max(0,Number(settings?.delivery_fee)||0):0,total=subtotal+deliveryFee,no=`EC-${Date.now()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`,invoiceNo=`ECINV-${Date.now()}-${Math.random().toString(36).slice(2,5).toUpperCase()}`,paymentStatus=method==='Cash on Delivery'?'unpaid':'pending_verification';
 for(const i of items){const reserved=await sql`UPDATE ecommerce_products SET stock_quantity=stock_quantity-${i.qty},updated_at=now() WHERE id=${i.product_id} AND stock_quantity>=${i.qty} RETURNING id`;if(!reserved[0]){for(const done of items.slice(0,items.indexOf(i)))await sql`UPDATE ecommerce_products SET stock_quantity=stock_quantity+${done.qty},updated_at=now() WHERE id=${done.product_id}`;return{status:409,data:{error:`${i.name}: required quantity available nahi hai`}}}}
 let out;try{out=await sql`INSERT INTO ecommerce_orders(order_number,invoice_number,customer_name,phone,email,fulfilment_type,delivery_address,payment_method,payment_reference,items,subtotal,delivery_fee,total,payment_status,notes) VALUES(${no},${invoiceNo},${name},${phone},${clean(b.email)},${fulfilment},${clean(b.delivery_address)},${method},${clean(b.payment_reference)},${JSON.stringify(items)},${subtotal},${deliveryFee},${total},${paymentStatus},${clean(b.notes)}) RETURNING *`}catch(e){for(const i of items)await sql`UPDATE ecommerce_products SET stock_quantity=stock_quantity+${i.qty},updated_at=now() WHERE id=${i.product_id}`;throw e}
 return{status:201,data:{record:out[0]}}}

async function publicCategories(sql){return sql`SELECT c.id,c.name,c.sort_order,c.status,COUNT(p.id) FILTER (WHERE p.status='active' AND p.sale_price>0 AND p.stock_quantity>0)::int product_count FROM ecommerce_categories c LEFT JOIN ecommerce_products p ON lower(COALESCE(p.category,''))=lower(c.name) WHERE c.status='active' GROUP BY c.id ORDER BY c.sort_order,c.name,c.id`}
async function manageCategories(sql,req){const b=body(req),id=asId(req.query?.id);if(req.method==='GET')return{status:200,data:{records:await sql`SELECT c.*,COUNT(p.id)::int product_count FROM ecommerce_categories c LEFT JOIN ecommerce_products p ON lower(COALESCE(p.category,''))=lower(c.name) GROUP BY c.id ORDER BY c.sort_order,c.name,c.id`}};const name=clean(b.name);if(req.method==='POST'){if(!name)return{status:400,data:{error:'Category name required hai'}};const rows=await sql`INSERT INTO ecommerce_categories(name,sort_order,status) VALUES(${name},${Math.trunc(Number(b.sort_order)||0)},${clean(b.status)||'active'}) RETURNING *`;return{status:201,data:{record:rows[0]}}}if(req.method==='PATCH'&&id){const cur=(await sql`SELECT * FROM ecommerce_categories WHERE id=${id}`)[0];if(!cur)return{status:404,data:{error:'Category not found'}};const next=name||cur.name;const rows=await sql`UPDATE ecommerce_categories SET name=${next},sort_order=${Math.trunc(Number(b.sort_order??cur.sort_order)||0)},status=${clean(b.status)||cur.status},updated_at=now() WHERE id=${id} RETURNING *`;if(next!==cur.name)await sql`UPDATE ecommerce_products SET category=${next},updated_at=now() WHERE lower(COALESCE(category,''))=lower(${cur.name})`;return{status:200,data:{record:rows[0]}}}if(req.method==='DELETE'&&id){const cur=(await sql`SELECT * FROM ecommerce_categories WHERE id=${id}`)[0];if(!cur)return{status:404,data:{error:'Category not found'}};const used=(await sql`SELECT COUNT(*)::int count FROM ecommerce_products WHERE lower(COALESCE(category,''))=lower(${cur.name})`)[0]?.count||0;if(used)return{status:409,data:{error:'Is category mein products mojood hain'}};await sql`DELETE FROM ecommerce_categories WHERE id=${id}`;return{status:200,data:{deleted:true}}}return{status:405,data:{error:'Method not allowed'}}}
async function publicPromotions(sql){return sql`SELECT id,title,subtitle,media_type,media_url,link_url,sort_order FROM ecommerce_promotions WHERE status='active' ORDER BY sort_order,id LIMIT 30`}
async function managePromotions(sql,req){const b=body(req),id=asId(req.query?.id);if(req.method==='GET')return{status:200,data:{records:await sql`SELECT * FROM ecommerce_promotions ORDER BY sort_order,id`}};if(req.method==='POST'){const url=clean(b.media_url),type=clean(b.media_type);if(!url||!['image','video'].includes(type))return{status:400,data:{error:'Valid media required hai'}};const rows=await sql`INSERT INTO ecommerce_promotions(title,subtitle,media_type,media_url,link_url,status,sort_order) VALUES(${clean(b.title)},${clean(b.subtitle)},${type},${url},${clean(b.link_url)},${clean(b.status)||'active'},${Math.trunc(Number(b.sort_order)||0)}) RETURNING *`;return{status:201,data:{record:rows[0]}}}if(req.method==='PATCH'&&id){const rows=await sql`UPDATE ecommerce_promotions SET title=CASE WHEN ${b.title!==undefined} THEN ${clean(b.title)} ELSE title END,subtitle=CASE WHEN ${b.subtitle!==undefined} THEN ${clean(b.subtitle)} ELSE subtitle END,media_type=COALESCE(${clean(b.media_type)},media_type),media_url=COALESCE(${clean(b.media_url)},media_url),link_url=CASE WHEN ${b.link_url!==undefined} THEN ${clean(b.link_url)} ELSE link_url END,status=COALESCE(${clean(b.status)},status),sort_order=COALESCE(${b.sort_order===undefined?null:Math.trunc(Number(b.sort_order)||0)},sort_order),updated_at=now() WHERE id=${id} RETURNING *`;return rows[0]?{status:200,data:{record:rows[0]}}:{status:404,data:{error:'Promotion not found'}}}if(req.method==='DELETE'&&id){const rows=await sql`DELETE FROM ecommerce_promotions WHERE id=${id} RETURNING id`;return{status:200,data:{deleted:Boolean(rows[0])}}}return{status:405,data:{error:'Method not allowed'}}}
async function manage(sql,req,user){if(req.method==='GET'){const status=clean(req.query?.status)||'all',rows=status==='all'?await sql`SELECT * FROM ecommerce_orders ORDER BY created_at DESC LIMIT 300`:await sql`SELECT * FROM ecommerce_orders WHERE status=${status} ORDER BY created_at DESC LIMIT 300`;return{status:200,data:{records:rows}}}
 const orderId=asId(req.query?.id),b=body(req);if(req.method!=='PATCH'||!orderId)return{status:405,data:{error:'Method not allowed'}};const current=(await sql`SELECT * FROM ecommerce_orders WHERE id=${orderId}`)[0];if(!current)return{status:404,data:{error:'Online order not found'}};
 
 const status=clean(b.status),paymentStatus=clean(b.payment_status),valid=['new','confirmed','ready','out_for_delivery','completed','cancelled'];if(status&&!valid.includes(status))return{status:400,data:{error:'Invalid order status'}};if(paymentStatus&&!['unpaid','pending_verification','paid'].includes(paymentStatus))return{status:400,data:{error:'Invalid payment status'}};if(status==='completed'&&(paymentStatus||current.payment_status)!=='paid')return{status:409,data:{error:'Order complete karne se pehle payment Paid mark karein'}};if(current.status==='cancelled'&&status&&status!=='cancelled')return{status:409,data:{error:'Cancelled order dobara open nahi ho sakta'}};if(status==='cancelled'&&current.status!=='cancelled'){for(const i of(Array.isArray(current.items)?current.items:JSON.parse(current.items||'[]')))await sql`UPDATE ecommerce_products SET stock_quantity=stock_quantity+${Number(i.qty)||0},updated_at=now() WHERE id=${asId(i.product_id)}`}
 const row=(await sql`UPDATE ecommerce_orders SET status=COALESCE(${status},status),payment_status=COALESCE(${paymentStatus},payment_status),amount_received=CASE WHEN ${paymentStatus}='paid' THEN total ELSE amount_received END,paid_by_name=CASE WHEN ${paymentStatus}='paid' THEN ${user.full_name||user.employee_code} ELSE paid_by_name END,paid_at=CASE WHEN ${paymentStatus}='paid' THEN now() ELSE paid_at END,updated_at=now() WHERE id=${orderId} RETURNING *`)[0];return{status:200,data:{record:row}}}
async function manageProducts(sql,req){const b=body(req),pid=asId(req.query?.id);if(req.method==='GET'){const rows=await sql`SELECT * FROM ecommerce_products ORDER BY category,name,id`;return{status:200,data:{records:rows}}}if(req.method==='POST'){const name=clean(b.name),price=Number(b.sale_price),stock=Number(b.stock_quantity),images=imageList(b.product_image_urls),primary=images[0]||clean(b.product_image_url),gallery=images.length?images:(primary?[primary]:[]);if(!name||!Number.isFinite(price)||price<0||!Number.isFinite(stock)||stock<0)return{status:400,data:{error:'Product name, valid price aur stock required hain'}};const sku=clean(b.sku)||`EC-P-${Date.now()}`,rows=await sql`INSERT INTO ecommerce_products(sku,name,category,description,unit,sale_price,stock_quantity,product_image_url,product_image_urls,status) VALUES(${sku},${name},${clean(b.category)},${clean(b.description)},${clean(b.unit)||'pcs'},${price},${stock},${primary},${JSON.stringify(gallery)}::jsonb,${clean(b.status)||'active'}) RETURNING *`;return{status:201,data:{record:rows[0]}}}if(req.method==='PATCH'&&pid){const hasGallery=Array.isArray(b.product_image_urls),images=imageList(b.product_image_urls),primary=hasGallery?(images[0]||null):clean(b.product_image_url);const rows=await sql`UPDATE ecommerce_products SET sku=COALESCE(${clean(b.sku)},sku),name=COALESCE(${clean(b.name)},name),category=${clean(b.category)},description=${clean(b.description)},unit=COALESCE(${clean(b.unit)},unit),sale_price=COALESCE(${b.sale_price===''?null:Number(b.sale_price)},sale_price),stock_quantity=COALESCE(${b.stock_quantity===''?null:Number(b.stock_quantity)},stock_quantity),product_image_url=CASE WHEN ${hasGallery} THEN ${primary} ELSE COALESCE(${primary},product_image_url) END,product_image_urls=CASE WHEN ${hasGallery} THEN ${JSON.stringify(images)}::jsonb ELSE product_image_urls END,status=COALESCE(${clean(b.status)},status),updated_at=now() WHERE id=${pid} RETURNING *`;return rows[0]?{status:200,data:{record:rows[0]}}:{status:404,data:{error:'E-Commerce product not found'}}}if(req.method==='DELETE'&&pid){const rows=await sql`DELETE FROM ecommerce_products WHERE id=${pid} RETURNING id`;return{status:200,data:{deleted:Boolean(rows[0])}}}return{status:405,data:{error:'Method not allowed'}}}

export default async function handler(req,res){try{const sql=db(),action=clean(req.query?.action)||'catalog';await schema(sql);if(req.method==='GET'&&action==='catalog')return res.status(200).json({records:await catalog(sql,req)});if(req.method==='GET'&&action==='categories'&&req.query?.manage!=='1')return res.status(200).json({records:await publicCategories(sql)});if(req.method==='GET'&&action==='promotions'&&req.query?.manage!=='1')return res.status(200).json({records:await publicPromotions(sql)});if(req.method==='GET'&&action==='config'){const rows=await sql`SELECT store_name,contact_phone,shop_address,bank_details,easypaisa_number,jazzcash_number,delivery_fee FROM ecommerce_settings WHERE id=1`;return res.status(200).json({record:rows[0]})}if(req.method==='POST'&&action==='order'){const out=await createOrder(sql,req);return res.status(out.status).json(out.data)};const user=await getSessionUser(req,sql);if(!user)return res.status(401).json({error:'Authentication required'});if(action==='products'){const out=await manageProducts(sql,req);return res.status(out.status).json(out.data)}if(action==='categories'){const out=await manageCategories(sql,req);return res.status(out.status).json(out.data)}if(action==='promotions'){const out=await managePromotions(sql,req);return res.status(out.status).json(out.data)}if(action==='settings'){if(req.method==='GET'){const rows=await sql`SELECT * FROM ecommerce_settings WHERE id=1`;return res.status(200).json({record:rows[0]})}if(req.method==='PATCH'){const b=body(req),rows=await sql`UPDATE ecommerce_settings SET store_name=COALESCE(${clean(b.store_name)},store_name),contact_phone=${clean(b.contact_phone)},shop_address=${clean(b.shop_address)},bank_details=${clean(b.bank_details)},easypaisa_number=${clean(b.easypaisa_number)},jazzcash_number=${clean(b.jazzcash_number)},delivery_fee=GREATEST(0,${Number(b.delivery_fee)||0}),updated_at=now() WHERE id=1 RETURNING *`;return res.status(200).json({record:rows[0]})}}const out=await manage(sql,req,user);return res.status(out.status).json(out.data)}catch(e){console.error('Ecommerce API error',e);return res.status(500).json({error:e?.message||'Ecommerce request failed'})}}

