'use strict';
(()=>{
 const DB_NAME='kt_offline_v2',STORE='queue',AUTH_KEY='kt_offline_user_v1',CACHE_PREFIX='kt_offline_cache:',OLD_KEY='kt_offline_queue_v1';
 const allowed=new Set(['suppliers','supplier_invoices','supplier_payments','clients','client_invoices','client_receipts','documents']);
 const nativeFetch=window.fetch.bind(window);let dbPromise=null;
 const uid=()=>globalThis.crypto?.randomUUID?.()||('kt-'+Date.now()+'-'+Math.random().toString(36).slice(2));
 const cacheKey=url=>CACHE_PREFIX+url;
 function notify(msg,bad=false){try{if(typeof toast==='function')toast(msg,bad)}catch{}}
 function openDb(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'qid'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return dbPromise}
 async function all(){try{const d=await openDb();return await new Promise((resolve,reject)=>{const r=d.transaction(STORE,'readonly').objectStore(STORE).getAll();r.onsuccess=()=>resolve((r.result||[]).sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at))));r.onerror=()=>reject(r.error)})}catch{return[]}}
 async function put(item){const d=await openDb();return new Promise((resolve,reject)=>{const r=d.transaction(STORE,'readwrite').objectStore(STORE).put(item);r.onsuccess=()=>resolve(item);r.onerror=()=>reject(r.error)})}
 async function del(qid){const d=await openDb();return new Promise((resolve,reject)=>{const r=d.transaction(STORE,'readwrite').objectStore(STORE).delete(qid);r.onsuccess=()=>resolve(true);r.onerror=()=>reject(r.error)})}
 async function migrate(){try{const raw=JSON.parse(localStorage.getItem(OLD_KEY)||'[]');for(const x of raw){if(x?.qid)await put({...x,method:x.method||'POST'})}if(raw.length)localStorage.removeItem(OLD_KEY)}catch{}}
 function resourceInfo(url){try{const u=new URL(url,location.origin);if(u.pathname!=='/api/data')return null;const resource=u.searchParams.get('resource'),id=Number(u.searchParams.get('id'));return {resource,id:Number.isInteger(id)&&id!==0?id:null,listUrl:u.pathname+'?resource='+encodeURIComponent(resource)}}catch{return null}}
 function cachedResponse(url){try{const raw=localStorage.getItem(cacheKey(url));if(!raw)return null;return new Response(raw,{status:200,headers:{'Content-Type':'application/json','X-KT-Offline-Cache':'1'}})}catch{return null}}
 async function remember(url,response){try{if(!response.ok)return;const type=response.headers.get('content-type')||'';if(!type.includes('application/json'))return;const text=await response.clone().text();if(text.length<1500000)localStorage.setItem(cacheKey(url),text)}catch{}}
 function mutateCache(info,method,body,tempId){try{const key=cacheKey(info.listUrl),raw=localStorage.getItem(key);if(!raw)return;const data=JSON.parse(raw),rows=Array.isArray(data.records)?data.records:[];if(method==='POST')rows.unshift({...body,id:tempId,_offline_pending:true});else if(method==='PATCH'){const i=rows.findIndex(x=>Number(x.id)===Number(info.id));if(i>=0)rows[i]={...rows[i],...body,_offline_pending:true}}else if(method==='DELETE')data.records=rows.filter(x=>Number(x.id)!==Number(info.id));if(method!=='DELETE')data.records=rows;localStorage.setItem(key,JSON.stringify(data))}catch{}}
 async function refreshBadge(extra=''){const q=await all(),n=q.length,failed=q.filter(x=>x.sync_error).length;let el=document.getElementById('ktOfflineBadge');if(!el){el=document.createElement('button');el.type='button';el.id='ktOfflineBadge';el.setAttribute('aria-label','Sync status');el.style.cssText='position:fixed;right:14px;bottom:18px;z-index:9998;min-width:46px;height:46px;padding:0 12px;border:1px solid #c79b2b;border-radius:999px;background:#174f43;color:#fff;font:700 11px system-ui;box-shadow:0 4px 14px #0004;display:flex;align-items:center;justify-content:center;gap:6px;overflow:hidden';el.innerHTML='<span data-sync-icon style="font-size:22px;line-height:1">↻</span><span data-sync-text></span><span data-sync-line style="position:absolute;left:0;bottom:0;height:3px;width:100%;background:linear-gradient(90deg,#d4af37,#fff,#2dbd83);transform:translateX(-100%);opacity:0"></span>';el.addEventListener('click',async e=>{e.preventDefault();e.stopPropagation();if(!navigator.onLine){await refreshBadge('Offline Mode');notify('Offline Mode — internet anay par sync ho ga.');return}el.style.pointerEvents='none';try{await refreshBadge('Syncing');await sync(true);const left=await all();if(!left.length){await refreshBadge('All synced');notify('All data synced.')}}finally{el.style.pointerEvents='auto'}});document.body.appendChild(el)}const icon=el.querySelector('[data-sync-icon]'),txt=el.querySelector('[data-sync-text]'),line=el.querySelector('[data-sync-line]'),syncing=Boolean(window.KT_OFFLINE_SYNCING);if(icon)icon.textContent=syncing?'↻':(!navigator.onLine?'×':'↻');if(txt)txt.textContent=failed?(failed+' Failed'):(n?(n+' Pending'):(extra&&extra!=='All synced'?extra:''));el.style.background=failed?'#8b2f2f':(!navigator.onLine?'#6b6252':'#174f43');el.style.display='flex';if(line){line.style.opacity=syncing?'1':'0';line.style.animation=syncing?'ktSyncLine 1s linear infinite':'none'}if(!document.getElementById('ktSyncStyle')){const s=document.createElement('style');s.id='ktSyncStyle';s.textContent='@keyframes ktSyncLine{0%{transform:translateX(-100%)}100%{transform:translateX(100%)}} @keyframes ktSyncSpin{to{transform:rotate(360deg)}} #ktOfflineBadge [data-sync-icon]{display:inline-block} #ktOfflineBadge.kt-syncing [data-sync-icon]{animation:ktSyncSpin .9s linear infinite}';document.head.appendChild(s)}el.classList.toggle('kt-syncing',syncing)}
 async function queueRequest(info,method,body){if(!allowed.has(info.resource)||!['POST','PATCH','DELETE'].includes(method))return null;let q=await all();if(info.id&&info.id<0){const parent=q.find(x=>x.method==='POST'&&Number(x.temp_id)===Number(info.id));if(parent){if(method==='PATCH'){parent.body={...(parent.body||{}),...(body||{})};parent.sync_error=null;await put(parent);mutateCache(info,'PATCH',body);await refreshBadge();notify('Offline entry update Pending Sync mein save ho gai.');return {offline_queued:true,pending_sync:true,queue_id:parent.qid}}if(method==='DELETE'){await del(parent.qid);mutateCache(info,'DELETE',{});await refreshBadge();notify('Offline pending entry remove ho gai.');return {offline_queued:true,pending_sync:false,cancelled:true}}}}
 const tempId=method==='POST'?-(Date.now()*1000+Math.floor(Math.random()*999)):null,item={qid:uid(),resource:info.resource,method,id:info.id,body:body||{},temp_id:tempId,created_at:new Date().toISOString(),sync_error:null};await put(item);mutateCache(info,method,item.body,tempId);await refreshBadge();notify(method==='DELETE'?'Delete Pending Sync mein save ho gaya.':method==='PATCH'?'Update Pending Sync mein save ho gai.':'Entry Pending Sync mein save ho gai.');return {offline_queued:true,pending_sync:true,queue_id:item.qid,temp_id:tempId}}
 function parseBody(init){try{return typeof init?.body==='string'?JSON.parse(init.body):init?.body||{}}catch{return{}}}
 function isApiCacheable(url){return /\/api\/data\?/.test(url)||/\/api\/(dashboard|approvals|salaries)/.test(url)}
 window.fetch=async function(input,init={}){
  const url=typeof input==='string'?input:input?.url||'',method=String(init?.method||input?.method||'GET').toUpperCase(),info=resourceInfo(url);const h=init?.headers,syncCall=Boolean(h&&((h['X-KT-Offline-ID'])||(h instanceof Headers&&h.get('X-KT-Offline-ID'))));
  if(info&&['POST','PATCH','DELETE'].includes(method)&&!syncCall&&!navigator.onLine){const x=await queueRequest(info,method,parseBody(init));if(x)return new Response(JSON.stringify(x),{status:method==='POST'?201:200,headers:{'Content-Type':'application/json','X-KT-Offline-Queued':'1'}})}
  if(method==='GET'&&!navigator.onLine&&isApiCacheable(url)){const c=cachedResponse(url);if(c)return c;return new Response(JSON.stringify({error:'Offline: no cached records available'}),{status:503,headers:{'Content-Type':'application/json'}})}
  try{const r=await nativeFetch(input,init);if(method==='GET'&&r.ok&&isApiCacheable(url))await remember(url,r);if(method==='POST'&&/\/api\/auth\?action=logout/.test(url)&&r.ok){localStorage.removeItem(AUTH_KEY);try{const d=await openDb();d.close();indexedDB.deleteDatabase(DB_NAME)}catch{}}return r}catch(e){if(info&&['POST','PATCH','DELETE'].includes(method)&&!syncCall){const x=await queueRequest(info,method,parseBody(init));if(x)return new Response(JSON.stringify(x),{status:method==='POST'?201:200,headers:{'Content-Type':'application/json','X-KT-Offline-Queued':'1'}})}if(method==='GET'){const c=cachedResponse(url);if(c)return c}throw e}
 };
 async function sync(force=false){if(!navigator.onLine||window.KT_OFFLINE_SYNCING)return;let q=await all();if(!q.length){await refreshBadge(force?'All synced':'');return}window.KT_OFFLINE_SYNCING=true;await refreshBadge('Syncing');let done=0,blocked=false;try{for(const item of q){try{const suffix=item.id?'&id='+encodeURIComponent(item.id):'',r=await nativeFetch('/api/data?resource='+encodeURIComponent(item.resource)+suffix,{method:item.method,cache:'no-store',headers:{'Content-Type':'application/json','X-KT-Offline-ID':item.qid},body:item.method==='DELETE'?undefined:JSON.stringify(item.body||{})});if(r.status===401||r.status===403){blocked=true;break}if(!r.ok){let msg='HTTP '+r.status;try{msg=(await r.json()).error||msg}catch{}await put({...item,sync_error:msg,last_attempt_at:new Date().toISOString()});continue}await del(item.qid);done++}catch(e){await put({...item,sync_error:e?.message||'Network error',last_attempt_at:new Date().toISOString()});break}}}finally{window.KT_OFFLINE_SYNCING=false;await refreshBadge()}if(done){notify(done+' offline entr'+(done===1?'y':'ies')+' sync ho '+(done===1?'gai':'gain')+'.');try{Object.keys(window.cache||{}).forEach(k=>delete window.cache[k]);if(typeof loadModule==='function'&&typeof currentView==='string'&&currentView!=='dashboard')loadModule(currentView);else if(typeof loadDashboard==='function'&&currentView==='dashboard')loadDashboard()}catch{}}if(blocked)notify('Pending Sync ke liye dobara login zaroori hai.',true)}
 window.KT_OFFLINE={sync,count:async()=>(await all()).length,items:all};
 window.addEventListener('online',()=>{refreshBadge('Online');setTimeout(()=>sync(),700)});window.addEventListener('offline',()=>refreshBadge('Offline Mode'));document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync()});
 migrate().then(()=>refreshBadge(navigator.onLine?'':'Offline Mode'));if(navigator.onLine)setTimeout(()=>sync(),1800);
})();
