'use strict';(()=>{
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=v=>'PKR '+Number(v||0).toLocaleString();
 const fmt=v=>v?new Date(v).toLocaleString():'—';
 const module=document.getElementById('module'),mt=document.getElementById('mt'),mp=document.getElementById('mp');
 async function api(url,opt){const r=await fetch(url,{cache:'no-store',headers:{'Content-Type':'application/json'},...opt});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed');return j}
 function toast(t){if(window.showToast)return window.showToast(t);alert(t)}
 function modal(html){let x=document.getElementById('salaryModal');if(x)x.remove();x=document.createElement('div');x.id='salaryModal';x.style.cssText='position:fixed;inset:0;background:#0008;z-index:9999;display:flex;align-items:center;justify-content:center;padding:16px';x.innerHTML='<div style="background:#fffdf5;color:#173f35;width:min(720px,100%);max-height:90vh;overflow:auto;border-radius:18px;padding:20px;box-shadow:0 24px 70px #0005">'+html+'</div>';document.body.appendChild(x);return x}
 async function render(){
  const j=await api('/api/salaries');const rows=j.records||[],admin=window.KT_USER?.designation==='admin';
  mt.textContent='Salary & Advances';mp.textContent=admin?'Review employee salary/advance requests, approve them and record payment.':'Request monthly salary or an advance from your own employee account.';
  module.innerHTML='<h2 id="mt">Salary & Advances</h2><p id="mp">'+esc(mp.textContent)+'</p><div style="display:flex;gap:10px;flex-wrap:wrap;margin:14px 0"><button class="primary" id="salaryNew">+ New Request</button><button id="salaryRefresh">Refresh</button></div><div class="tablewrap"><table><thead><tr><th>Employee</th><th>Type</th><th>Month</th><th>Amount</th><th>Status</th><th>Requested</th><th>Action</th></tr></thead><tbody>'+rows.map(r=>'<tr><td><b>'+esc(r.employee_name)+'</b><br><small>'+esc(r.employee_code)+' · '+esc(r.designation)+'</small></td><td>'+esc(r.request_type==='monthly_salary'?'Monthly Salary':'Salary Advance')+'</td><td>'+esc(r.salary_month?String(r.salary_month).slice(0,7):'—')+'</td><td><b>'+money(r.amount)+'</b></td><td>'+esc(String(r.status).toUpperCase())+'</td><td>'+esc(fmt(r.requested_at))+'</td><td>'+(admin&&r.status==='pending'?'<button data-sa="approve" data-id="'+r.id+'">Approve</button> <button data-sa="reject" data-id="'+r.id+'">Reject</button>':admin&&r.status==='approved'?'<button data-sa="pay" data-id="'+r.id+'">Record Payment</button>':'—')+'</td></tr>').join('')+'</tbody></table></div>';
  document.getElementById('salaryNew').style.display=admin?'none':'';document.getElementById('salaryNew').onclick=openRequest;document.getElementById('salaryRefresh').onclick=render;
  module.querySelectorAll('[data-sa]').forEach(b=>b.onclick=()=>review(b.dataset.id,b.dataset.sa));
 }
 function openRequest(){const x=modal('<h2>Salary / Advance Request</h2><p>Your employee ID, name and designation are recorded automatically.</p><label>Request Type</label><select id="srType"><option value="salary_advance">Salary Advance</option><option value="monthly_salary">Monthly Salary</option></select><label>Salary Month</label><input id="srMonth" type="month"><label>Amount (PKR)</label><input id="srAmount" type="number" min="1" step="0.01" placeholder="Amount"><label>Reason / Note</label><textarea id="srReason" rows="3" placeholder="Reason for request"></textarea><div style="display:flex;gap:10px;margin-top:16px"><button class="primary" id="srSend">Send for Admin Approval</button><button id="srClose">Cancel</button></div>');x.querySelector('#srClose').onclick=()=>x.remove();x.querySelector('#srSend').onclick=async()=>{try{const type=x.querySelector('#srType').value,month=x.querySelector('#srMonth').value;x.querySelector('#srSend').disabled=true;await api('/api/salaries',{method:'POST',body:JSON.stringify({request_type:type,salary_month:month?month+'-01':null,amount:x.querySelector('#srAmount').value,reason:x.querySelector('#srReason').value})});x.remove();toast('Sent to Admin for approval');await render()}catch(e){toast(e.message);x.querySelector('#srSend').disabled=false}}}
 async function review(id,action){try{if(action==='pay'){const x=modal('<h2>Record Salary Payment</h2><label>Payment Method</label><select id="spMethod"><option>Cash</option><option>Bank Transfer</option><option>Cheque</option><option>Other</option></select><label>Reference</label><input id="spRef" placeholder="Voucher / transaction reference"><div style="display:flex;gap:10px;margin-top:16px"><button class="primary" id="spPay">Mark Paid</button><button id="spClose">Cancel</button></div>');x.querySelector('#spClose').onclick=()=>x.remove();x.querySelector('#spPay').onclick=async()=>{try{await api('/api/salaries?id='+id,{method:'PATCH',body:JSON.stringify({action:'pay',payment_method:x.querySelector('#spMethod').value,payment_reference:x.querySelector('#spRef').value})});x.remove();toast('Payment recorded');await render()}catch(e){toast(e.message)}};return}await api('/api/salaries?id='+id,{method:'PATCH',body:JSON.stringify({action})});toast(action==='approve'?'Salary request approved':'Salary request rejected');await render()}catch(e){toast(e.message)}}
 document.addEventListener('click',e=>{const b=e.target.closest('#nav [data-view="salary-advances"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();document.getElementById('dashboard')?.classList.add('hidden');module?.classList.remove('hidden');document.querySelectorAll('#nav [data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');render().catch(e=>toast(e.message))},true);
})();
