import test from 'node:test';
import assert from 'node:assert/strict';
import { replayOnce } from '../offline-replay-core.js';
function setup(){const records=new Map();return {records,store:{async claim(owner,key,fingerprint){const k=owner+':'+key;if(records.has(k))return false;records.set(k,{fingerprint,state:'claimed'});return true;},async read(owner,key){return records.get(owner+':'+key);},async complete(owner,key,status,data){Object.assign(records.get(owner+':'+key),{state:'complete',http_status:status,response:data});}}};}
const base={owner:'1',key:'operation-1234',method:'POST',url:'/api/data?resource=cash_sales',body:{amount:480}};
test('lost response retry returns original record without another posting',async()=>{const{store}=setup();let postings=0;const request={...base,store,execute:async()=>({status:201,data:{record:{id:++postings}}})};assert.deepEqual(await replayOnce(request),await replayOnce(request));assert.equal(postings,1);});
test('concurrent duplicate executes only once',async()=>{const{store}=setup();let calls=0;const request={...base,store,execute:async()=>{calls++;await new Promise(r=>setTimeout(r,10));return{status:201,data:{record:{id:1}}};}};const results=await Promise.all([replayOnce(request),replayOnce(request)]);assert.equal(calls,1);assert.deepEqual(results.map(x=>x.status).sort(),[201,409]);});
test('crash after posting is retained for review and never auto-replayed',async()=>{const{store}=setup();let postings=0;const request={...base,store,execute:async()=>{postings++;throw Error('process failed');}};await assert.rejects(replayOnce(request));assert.equal((await replayOnce(request)).data.sync_state,'review');assert.equal(postings,1);});
test('payload mismatch cannot reuse operation ID',async()=>{const{store}=setup();const request={...base,store,execute:async()=>({status:200,data:{ok:true}})};await replayOnce(request);assert.equal((await replayOnce({...request,body:{amount:960}})).status,409);});
test('employees do not share response records',async()=>{const{store}=setup();let calls=0;const request={...base,store,execute:async()=>({status:201,data:{id:++calls}})};await replayOnce(request);await replayOnce({...request,owner:'2'});assert.equal(calls,2);});
