import { getVercelOidcToken } from '@vercel/oidc';

const baseFields=['invoice_number','date','due_date','amount','reference_number','bank','document_type','party_name','notes'];
const clean=v=>String(v??'').trim().slice(0,500);
const digits=v=>String(v??'').replace(/[^0-9.]/g,'').slice(0,40);
function parseJson(text){const raw=String(text||'').trim();if(!raw)return null;const tries=[raw,raw.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'')];const a=raw.indexOf('{'),b=raw.lastIndexOf('}');if(a>=0&&b>a)tries.push(raw.slice(a,b+1));for(const t of tries){try{return JSON.parse(t)}catch{}}return null}
function responseText(j){if(typeof j?.output_text==='string'&&j.output_text.trim())return j.output_text;const p=[];for(const item of j?.output||[]){if(typeof item?.text==='string')p.push(item.text);if(typeof item?.text?.value==='string')p.push(item.text.value);for(const c of item?.content||[]){if(typeof c?.text==='string')p.push(c.text);if(typeof c?.text?.value==='string')p.push(c.text.value);if(typeof c?.output_text==='string')p.push(c.output_text);if(typeof c?.output_text?.value==='string')p.push(c.output_text.value)}}return p.filter(Boolean).join('\n')}
async function gatewayToken(){let token=process.env.AI_GATEWAY_API_KEY||process.env.VERCEL_OIDC_TOKEN||'';if(!token){try{token=await getVercelOidcToken()||''}catch(e){console.error('OIDC token error',e?.message||e)}}return token}
function inputPart(dataUrl){const s=String(dataUrl||'');if(/^data:image\/(jpeg|jpg|png|webp);base64,/i.test(s))return{type:'input_image',image_url:s};const m=s.match(/^data:application\/pdf;base64,(.+)$/i);if(m)return{type:'input_file',filename:'document.pdf',file_data:m[1]};throw new Error('UNSUPPORTED_DOCUMENT')}
const schema={type:'object',properties:{...Object.fromEntries(baseFields.map(k=>[k,{type:'string'}])),handwritten_total:{type:'string'},line_items:{type:'array',items:{type:'object',properties:{description:{type:'string'},amount:{type:'string'}},required:['description','amount'],additionalProperties:false}}},required:[...baseFields,'handwritten_total','line_items'],additionalProperties:false};
function promptFor(kind){const base=`Read this ${kind.replaceAll('_',' ')}. Extract only visible facts. Dates must be YYYY-MM-DD. Numeric amounts must contain digits only with optional decimal, no commas or currency symbols. Use empty string when unknown. Never guess.`;if(kind==='supplier_invoice')return `${base} party_name is the supplier/vendor business name. invoice_number is the supplier's own invoice/bill number. For date, look specifically for labels such as Invoice Date, Bill Date, Date, Dated, or the clearly printed invoice date near the invoice number/header. Normalize visible formats such as DD/MM/YYYY, DD-MM-YYYY, YYYY/MM/DD, or DD Mon YYYY into YYYY-MM-DD. Do not use due date as date. If the invoice date is not clearly visible, leave date empty. due_date must only contain an explicitly visible due date. amount is the visible invoice total or grand total.`;if(kind==='client_invoice')return `${base} party_name is the customer/client business name near the top. Leave due_date empty unless explicitly written. line_items must contain every visible billed row in top-to-bottom order with only description and final row amount; do not return quantity or rate. If description is unreadable, use Item 1, Item 2, etc. handwritten_total is the total explicitly written on the source bill; do not calculate it. amount is the visible invoice total when explicitly shown.`;if(kind==='supplier_bank_payment')return `${base} party_name is the beneficiary/recipient supplier. reference_number is the transaction/reference/trace number. bank is the receiving or clearly branded bank name.`;if(kind==='client_bank_receipt')return `${base} party_name is the payer/sender client. reference_number is the transaction/reference/trace number. bank is the clearly visible bank name.`;return `${base} For invoice use invoice_number; for bank document use reference_number and bank.`}
export async function extractDocument(dataUrl,kind='business_document'){const part=inputPart(dataUrl),token=await gatewayToken();if(!token)throw new Error('OCR_AUTH_UNAVAILABLE');const body={model:'openai/gpt-5-mini',input:[{role:'user',content:[{type:'input_text',text:promptFor(kind)},part]}],reasoning:{effort:'low'},max_output_tokens:1400,text:{format:{type:'json_schema',name:'document_fields',strict:true,schema}}};const r=await fetch('https://ai-gateway.vercel.sh/v1/responses',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok){console.error('OCR provider error',r.status,j?.error?.message||j?.error||'unknown');throw new Error('OCR_PROVIDER')}const parsed=parseJson(responseText(j));if(!parsed)throw new Error('OCR_PARSE_FAILED');const safe={};for(const k of baseFields)safe[k]=clean(parsed[k]);safe.handwritten_total=digits(parsed.handwritten_total);safe.line_items=Array.isArray(parsed.line_items)?parsed.line_items.slice(0,80).map((x,i)=>({description:clean(x?.description)||`Item ${i+1}`,amount:digits(x?.amount)})).filter(x=>x.amount):[];return safe}
