import { neon } from "@neondatabase/serverless";
import crypto from "node:crypto";
const db=()=>neon(process.env.DATABASE_URL);
const bodyOf=req=>{if(!req.body)return{};if(typeof req.body==="string"){try{return JSON.parse(req.body)}catch{return{}}}return req.body};
const clean=v=>v==null?null:String(v).trim()||null;
const hash=(v,s)=>crypto.scryptSync(String(v),s,64).toString("hex");
const token=()=>crypto.randomBytes(32).toString("hex");
const tokenHash=v=>crypto.createHash("sha256").update(v).digest("hex");
function cookie(req,n){const h=String(req.headers?.cookie||"").split(";").map(x=>x.trim()).find(x=>x.startsWith(n+"="));return h?decodeURIComponent(h.slice(n.length+1)):null}
async function schema(sql){
 await sql`ALTER TABLE cash_sale_customers ADD COLUMN IF NOT EXISTS portal_pin_salt TEXT`;
 await sql`ALTER TABLE cash_sale_customers ADD COLUMN IF NOT EXISTS portal_pin_hash TEXT`;
 await sql`CREATE TABLE IF NOT EXISTS cash_customer_sessions(id BIGSERIAL PRIMARY KEY,customer_id BIGINT NOT NULL REFERENCES cash_sale_customers(id) ON DELETE CASCADE,token_hash TEXT UNIQUE NOT NULL,expires_at TIMESTAMPTZ NOT NULL,last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),created_at TIMESTAMPTZ NOT NULL DEFAULT now())`;
 await sql`CREATE TABLE IF NOT EXISTS cash_customer_orders(id BIGSERIAL PRIMARY KEY,order_number TEXT UNIQUE NOT NULL,customer_id BIGINT NOT NULL REFERENCES cash_sale_customers(id),items JSONB NOT NULL DEFAULT '[]'::jsonb,status TEXT NOT NULL DEFAULT 'pending',cash_sale_id BIGINT REFERENCES cash_sale_queue(id),created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now())`;
}
async function customer(req,sql){const t=cookie(req,"kt_customer");if(!t)return null;const r=await sql`SELECT c.* FROM cash_customer_sessions s JOIN cash_sale_customers c ON c.id=s.customer_id WHERE s.token_hash=${tokenHash(t)} AND s.expires_at>now() AND c.status='active' LIMIT 1`;return r[0]||null}
const safeItems=v=>(Array.isArray(v)?v:[]).map(x=>({product_id:Number(x.product_id)||null,name:clean(x.name)||"Product",qty:Math.max(0,Number(x.qty)||0),unit:clean(x.unit)||"pcs"})).filter(x=>x.product_id&&x.qty>0).slice(0,100);
export default async function handler(req,res){try{const sql=db();await schema(sql);const action=clean(req.query?.action)||"dashboard",b=bodyOf(req);
 if(req.method==="POST"&&action==="login"){const code=clean(b.customer_code),pin=clean(b.pin);const c=(await sql`SELECT * FROM cash_sale_customers WHERE upper(customer_code)=upper(${code}) AND status='active' LIMIT 1`)[0];if(!c)return res.status(401).json({error:"Customer code ya PIN ghalat hai"});if(!c.portal_pin_hash)return res.status(409).json({error:"Portal PIN abhi set nahi hai. Kashif Traders se PIN activate karwain."});if(hash(pin,c.portal_pin_salt)!==c.portal_pin_hash)return res.status(401).json({error:"Customer code ya PIN ghalat hai"});const t=token();await sql`INSERT INTO cash_customer_sessions(customer_id,token_hash,expires_at) VALUES(${c.id},${tokenHash(t)},now()+interval '30 days')`;res.setHeader("Set-Cookie",`kt_customer=${encodeURIComponent(t)}; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=2592000`);return res.status(200).json({ok:true,name:c.name})}
 if(req.method==="POST"&&action==="logout"){const t=cookie(req,"kt_customer");if(t)await sql`DELETE FROM cash_customer_sessions WHERE token_hash=${tokenHash(t)}`;res.setHeader("Set-Cookie","kt_customer=; Path=/; HttpOnly; SameSite=Lax; Secure; Max-Age=0");return res.status(200).json({ok:true})}
 const c=await customer(req,sql);if(!c)return res.status(401).json({error:"Customer login required"});
 if(req.method==="GET"&&action==="products"){const rows=await sql`SELECT id,name,category,unit FROM cash_sale_products WHERE status='active' ORDER BY name,id LIMIT 500`;return res.status(200).json({records:rows})}
 if(req.method==="POST"&&action==="order"){const items=safeItems(b.items);if(!items.length)return res.status(400).json({error:"Kam az kam aik product aur quantity add karein"});const ids=items.map(x=>x.product_id),valid=await sql`SELECT id,name,unit FROM cash_sale_products WHERE id=ANY(${ids}) AND status='active'`;const map=new Map(valid.map(x=>[Number(x.id),x]));const final=items.filter(x=>map.has(x.product_id)).map(x=>({...x,name:map.get(x.product_id).name,unit:map.get(x.product_id).unit}));if(!final.length)return res.status(400).json({error:"Valid products required"});const no="CO-"+Date.now();const r=await sql`INSERT INTO cash_customer_orders(order_number,customer_id,items) VALUES(${no},${c.id},${JSON.stringify(final)}) RETURNING id,order_number,status,created_at`;return res.status(201).json({record:r[0]})}
 if(req.method==="GET"&&action==="dashboard"){const bills=await sql`SELECT id,invoice_number,sale_date,items,total,COALESCE(amount_received,0) amount_received,GREATEST(total-COALESCE(amount_received,0),0) balance_due,status,created_at FROM cash_sale_queue WHERE customer_id=${c.id} AND status IN ('paid','partial','credit') ORDER BY created_at DESC,id DESC LIMIT 200`;const orders=await sql`SELECT id,order_number,items,status,cash_sale_id,created_at FROM cash_customer_orders WHERE customer_id=${c.id} ORDER BY created_at DESC,id DESC LIMIT 100`;const outstanding=bills.reduce((n,x)=>n+Number(x.balance_due||0),0),sales=bills.reduce((n,x)=>n+Number(x.total||0),0),received=bills.reduce((n,x)=>n+Number(x.amount_received||0),0);return res.status(200).json({customer:{customer_code:c.customer_code,name:c.name,mobile:c.mobile},summary:{sales,received,outstanding},bills,orders})}
 if(req.method==="GET"&&action==="materials"){const days=Math.min(365,Math.max(1,Number(req.query?.days)||30));const rows=await sql`SELECT x->>'name' product,COALESCE(x->>'unit','pcs') unit,SUM(COALESCE((x->>'qty')::numeric,0)) quantity FROM cash_sale_queue q CROSS JOIN LATERAL jsonb_array_elements(q.items) x WHERE q.customer_id=${c.id} AND q.status IN ('paid','partial','credit') AND q.sale_date>=CURRENT_DATE-${days}::int GROUP BY x->>'name',COALESCE(x->>'unit','pcs') ORDER BY product`;return res.status(200).json({days,records:rows})}
 return res.status(405).json({error:"Method not allowed"});
}catch(e){console.error(e);return res.status(500).json({error:e?.message||"Customer portal failed"})}}