import crypto from 'node:crypto';
import { neon } from '@neondatabase/serverless';
import { extractDocument } from './_ocr-core.js';
import { downloadWhatsAppDocument } from './_whatsapp.js';

export const config={api:{bodyParser:false}};
const digits=v=>String(v||'').replace(/\D/g,'');
const clean=v=>String(v??'').trim();
const amount=v=>{const n=Number(String(v??'').replace(/,/g,''));return Number.isFinite(n)?n:null};
async function rawBody(req){const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>1200000)throw Error('WEBHOOK_TOO_LARGE');chunks.push(c)}return Buffer.concat(chunks)}
function validSignature(raw,req){const secret=clean(process.env.WHATSAPP_APP_SECRET);if(!secret)return true;const got=clean(req.headers['x-hub-signature-256']);if(!got.startsWith('sha256='))return false;const expected='sha256='+crypto.createHmac('sha256',secret).update(raw).digest('hex');const a=Buffer.from(got),b=Buffer.from(expected);return a.length===b.length&&crypto.timingSafeEqual(a,b)}
async function ensure(sql){await sql`CREATE TABLE IF NOT EXISTS whatsapp_intake (id BIGSERIAL PRIMARY KEY,message_id TEXT UNIQUE,from_number TEXT,from_name TEXT,message_type TEXT,attachment_url TEXT,message_text TEXT,processing_status TEXT NOT NULL DEFAULT 'received',matched_party_type TEXT,matched_party_id BIGINT,ocr_data JSONB,approval_id BIGINT,error_message TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_at TIMESTAMPTZ NOT NULL DEFAULT now())`}
async function matchSupplier(sql,from){const d=digits(from);if(!d)return null;const rows=await sql`SELECT id,business_name,whatsapp_number,mobile_number FROM suppliers WHERE status='active' ORDER BY id`;return rows.find(x=>{const w=digits(x.whatsapp_number),m=digits(x.mobile_number);return (w&&d.endsWith(w.slice(-10)))||(m&&d.endsWith(m.slice(-10)))})||null}
async function automationOwner(sql){const rows=await sql`SELECT id FROM employees WHERE designation='admin' AND status='active' ORDER BY id LIMIT 1`;return rows[0]?.id||null}
async function persistMedia(media,mediaId){const m=String(media.dataUrl||'').match(/^data:(image\/(?:jpeg|png|webp)|application\/pdf);base64,(.+)$/i);if(!m)return null;const buf=Buffer.from(m[2],'base64'),type=m[1].toLowerCase();if(process.env.BLOB_READ_WRITE_TOKEN){try{const {put}=await import('@vercel/blob');const ext=type==='application/pdf'?'pdf':type.includes('png')?'png':type.includes('webp')?'webp':'jpg';const blob=await put(`kashif-traders/whatsapp-invoices/${Date.now()}-${clean(mediaId)}.${ext}`,buf,{access:'public',contentType:type,addRandomSuffix:true});return blob.url}catch(e){console.error('WhatsApp invoice blob upload failed',e)}}return buf.length<=750000?media.dataUrl:null}
async function pendingDuplicate(sql,supplierId,invoiceNumber){if(!invoiceNumber)return false;const rows=await sql`SELECT id FROM approval_requests WHERE status='pending' AND resource_key='supplier_invoices' AND action='CREATE' AND COALESCE(new_data->>'supplier_id','')=${String(supplierId)} AND lower(COALESCE(new_data->>'invoice_number',''))=lower(${invoiceNumber}) LIMIT 1`;return Boolean(rows[0])}
function onboardingPage(){const app=clean(process.env.WHATSAPP_APP_ID||process.env.META_APP_ID),cfg=clean(process.env.WHATSAPP_CONFIG_ID||process.env.META_WHATSAPP_CONFIG_ID),ok=Boolean(app&&cfg);return `<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kashif Traders WhatsApp</title><style>body{font-family:system-ui;background:#f5f7fb;padding:24px;color:#14213d}.c{max-width:520px;margin:8vh auto;background:white;padding:28px;border-radius:20px;box-shadow:0 12px 40px #0001}button{width:100%;padding:14px;border:0;border-radius:12px;background:#1877f2;color:white;font-weight:700}button:disabled{opacity:.5}#s{margin-top:16px;padding:12px;background:#f1f4f8;border-radius:10px;white-space:pre-wrap}</style><div class="c"><h2>Kashif Traders · WhatsApp Coexistence</h2><p>Connect the existing WhatsApp Business App number through Meta Embedded Signup. Do not delete or unregister the current WhatsApp account.</p>${ok?'':'<p><b>Meta App ID / Embedded Signup Config ID is not configured in Vercel yet.</b></p>'}<button id="b" ${ok?'':'disabled'}>Connect existing WhatsApp Business</button><div id="s">Ready.</div></div><script>const A=${JSON.stringify(app)},C=${JSON.stringify(cfg)},s=document.querySelector('#s'),b=document.querySelector('#b');let session={};addEventListener('message',e=>{if(!['https://www.facebook.com','https://web.facebook.com'].includes(e.origin))return;try{let d=typeof e.data==='string'?JSON.parse(e.data):e.data;if(d?.type==='WA_EMBEDDED_SIGNUP'){session=d.data||{};s.textContent='Meta signup received…'}}catch{}});window.fbAsyncInit=()=>FB.init({appId:A,autoLogAppEvents:true,xfbml:true,version:'v23.0'});let j=document.createElement('script');j.src='https://connect.facebook.net/en_US/sdk.js';document.head.appendChild(j);b.onclick=()=>{if(!window.FB)return s.textContent='Meta SDK is loading. Try again.';FB.login(async r=>{let code=r?.authResponse?.code;if(!code)return s.textContent='Signup cancelled or no authorization code returned.';let x=await fetch('/api/whatsapp-webhook?coexistence=complete',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,session})}),o=await x.json();s.textContent=x.ok?'Connected successfully.\nPhone Number ID: '+(o.phone_number_id||'received'):(o.error||'Connection failed')},{config_id:C,response_type:'code',override_default_response_type:true,extras:{featureType:'whatsapp_business_app_onboarding',sessionInfoVersion:'3'}})};</script>`}
async function completeCoexistence(raw,res){const body=JSON.parse(raw.toString('utf8')||'{}'),code=clean(body.code),session=body.session&&typeof body.session==='object'?body.session:{};if(!code)return res.status(400).json({error:'Missing authorization code'});const app=clean(process.env.WHATSAPP_APP_ID||process.env.META_APP_ID),secret=clean(process.env.WHATSAPP_APP_SECRET||process.env.META_APP_SECRET);if(!app||!secret)return res.status(503).json({error:'Meta App ID / App Secret is not configured'});const v=clean(process.env.WHATSAPP_GRAPH_VERSION)||'v23.0',u=new URL(`https://graph.facebook.com/${v}/oauth/access_token`);u.searchParams.set('client_id',app);u.searchParams.set('client_secret',secret);u.searchParams.set('code',code);const r=await fetch(u),data=await r.json();if(!r.ok||!data.access_token)return res.status(502).json({error:data?.error?.message||'Meta code exchange failed'});const db=clean(process.env.DATABASE_URL);if(db){const sql=neon(db);await sql`CREATE TABLE IF NOT EXISTS whatsapp_connection (id BIGSERIAL PRIMARY KEY,provider TEXT NOT NULL DEFAULT 'meta',waba_id TEXT,phone_number_id TEXT,business_id TEXT,coexistence BOOLEAN NOT NULL DEFAULT true,status TEXT NOT NULL DEFAULT 'connected',raw_session JSONB,updated_at TIMESTAMPTZ NOT NULL DEFAULT now())`;await sql`INSERT INTO whatsapp_connection(waba_id,phone_number_id,business_id,raw_session) VALUES(${clean(session.waba_id||session.wabaId)||null},${clean(session.phone_number_id||session.phoneNumberId)||null},${clean(session.business_id||session.businessId)||null},${JSON.stringify(session)}::jsonb)`}return res.status(200).json({connected:true,coexistence:true,waba_id:clean(session.waba_id||session.wabaId)||null,phone_number_id:clean(session.phone_number_id||session.phoneNumberId)||null})}
export default async function handler(req,res){
 if(req.method==='GET'&&clean(req.query?.coexistence)==='start'){res.setHeader('content-type','text/html; charset=utf-8');return res.status(200).send(onboardingPage())}
 if(req.method==='GET'){if(clean(req.query?.['hub.mode'])!=='subscribe')return res.status(400).send('Bad request');if(clean(req.query?.['hub.verify_token'])!==clean(process.env.WHATSAPP_VERIFY_TOKEN))return res.status(403).send('Forbidden');return res.status(200).send(clean(req.query?.['hub.challenge']))}
 if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
 try{
  const raw=await rawBody(req);if(clean(req.query?.coexistence)==='complete')return await completeCoexistence(raw,res);if(!validSignature(raw,req))return res.status(401).json({error:'Invalid webhook signature'});
  const body=JSON.parse(raw.toString('utf8')||'{}'),value=body?.entry?.[0]?.changes?.[0]?.value||{},msg=value?.messages?.[0];if(!msg)return res.status(200).json({received:true});
  const db=process.env.DATABASE_URL;if(!db)return res.status(503).json({error:'Database is not configured'});const sql=neon(db);await ensure(sql);
  const mid=clean(msg.id),from=clean(msg.from),name=clean(value?.contacts?.[0]?.profile?.name),type=clean(msg.type),text=clean(msg?.text?.body||msg?.image?.caption||msg?.document?.caption||'');
  const existing=mid?await sql`SELECT id FROM whatsapp_intake WHERE message_id=${mid}`:[];if(existing[0])return res.status(200).json({received:true,duplicate:true});
  const inserted=await sql`INSERT INTO whatsapp_intake(message_id,from_number,from_name,message_type,message_text) VALUES(${mid||null},${from},${name||null},${type||null},${text||null}) RETURNING id`;const intakeId=inserted[0].id;
  const supplier=await matchSupplier(sql,from);if(!supplier){await sql`UPDATE whatsapp_intake SET processing_status='needs_review',error_message='Supplier WhatsApp number not matched',updated_at=now() WHERE id=${intakeId}`;return res.status(200).json({received:true,status:'needs_review'})}
  const mediaId=clean(msg?.image?.id||msg?.document?.id||'');if(!mediaId){await sql`UPDATE whatsapp_intake SET processing_status='needs_review',matched_party_type='supplier',matched_party_id=${supplier.id},error_message='Invoice image/PDF not present',updated_at=now() WHERE id=${intakeId}`;return res.status(200).json({received:true,status:'needs_review'})}
  const declared=clean(msg?.document?.mime_type||msg?.image?.mime_type);if(type==='document'&&declared&&!['application/pdf','image/jpeg','image/png','image/webp'].includes(declared)){await sql`UPDATE whatsapp_intake SET processing_status='needs_review',matched_party_type='supplier',matched_party_id=${supplier.id},error_message='Unsupported invoice document type',updated_at=now() WHERE id=${intakeId}`;return res.status(200).json({received:true,status:'needs_review'})}
  const media=await downloadWhatsAppDocument(mediaId),fields=await extractDocument(media.dataUrl,'supplier_invoice'),total=amount(fields.amount),attachmentUrl=await persistMedia(media,mediaId);
  if(!total){await sql`UPDATE whatsapp_intake SET processing_status='needs_review',matched_party_type='supplier',matched_party_id=${supplier.id},attachment_url=${attachmentUrl||('whatsapp-media:'+mediaId)},ocr_data=${JSON.stringify(fields)}::jsonb,error_message='Invoice amount could not be read',updated_at=now() WHERE id=${intakeId}`;return res.status(200).json({received:true,status:'needs_review'})}
  if(fields.invoice_number){const dup=await sql`SELECT id FROM supplier_invoices WHERE supplier_id=${supplier.id} AND lower(invoice_number)=lower(${fields.invoice_number}) LIMIT 1`;if(dup[0]||await pendingDuplicate(sql,supplier.id,fields.invoice_number)){await sql`UPDATE whatsapp_intake SET processing_status='duplicate',matched_party_type='supplier',matched_party_id=${supplier.id},attachment_url=${attachmentUrl||('whatsapp-media:'+mediaId)},ocr_data=${JSON.stringify(fields)}::jsonb,error_message='Duplicate supplier invoice number',updated_at=now() WHERE id=${intakeId}`;return res.status(200).json({received:true,status:'duplicate'})}}
  const newData={supplier_id:supplier.id,invoice_number:fields.invoice_number||null,invoice_date:fields.date||new Date().toISOString().slice(0,10),due_date:fields.due_date||null,amount:total,notes:`WhatsApp invoice from ${supplier.business_name}${fields.notes?' — '+fields.notes:''}`,attachment_url:attachmentUrl,status:'unpaid'};
  const ownerId=await automationOwner(sql);const approval=await sql`INSERT INTO approval_requests(requested_by_employee_id,requested_by_code,requested_by_name,requested_by_designation,module_key,resource_key,action,new_data) VALUES(${ownerId},'WHATSAPP','WhatsApp Intake','automation','supplier-bills','supplier_invoices','CREATE',${JSON.stringify(newData)}::jsonb) RETURNING id`;
  await sql`UPDATE whatsapp_intake SET processing_status='pending_approval',matched_party_type='supplier',matched_party_id=${supplier.id},attachment_url=${attachmentUrl||('whatsapp-media:'+mediaId)},ocr_data=${JSON.stringify(fields)}::jsonb,approval_id=${approval[0].id},updated_at=now() WHERE id=${intakeId}`;
  return res.status(200).json({received:true,status:'pending_approval'});
 }catch(e){console.error('WhatsApp intake error',e);return res.status(200).json({received:true,status:'error'})}
}
